return {
    {name = "Auckland Tower", address = "https://www.liveatc.net/play/nzaa_twr.pls", favorite = false},
    {name = "HF CAR-B: 11.330", address = "https://www.liveatc.net/play/hf_nh_11330.pls", favorite = false},
    {name = "HF NAT-B 5616/8864 NH", address = "https://www.liveatc.net/play/hf_atlantic_b.pls", favorite = false},
    {name = "NTS - Expansions", address = "https://stream-mixtape-geo.ntslive.net/mixtape3", favorite = false},
    {name = "NTS - Field Recordings", address = "https://stream-relay-geo.ntslive.net/mixtape23", favorite = false},
    {name = "NTS - Labyrinth", address = "https://stream-relay-geo.ntslive.net/mixtape31", favorite = false},
    {name = "NTS - Radio 1", address = "https://stream-relay-geo.ntslive.net/stream", favorite = false},
    {name = "NTS - Radio 2", address = "https://stream-relay-geo.ntslive.net/stream2", favorite = false},
    {name = "NTS - Sheet Music", address = "https://stream-relay-geo.ntslive.net/mixtape35", favorite = false},
    {name = "NTS - The Tube", address = "https://stream-relay-geo.ntslive.net/mixtape26", favorite = false},
    {name = "Novosibirsk Gnd/Twr/App/Radar/Misc", address = "https://www.liveatc.net/play/unnt.pls", favorite = false},
    {name = "RJAA Tower 1", address = "https://www.liveatc.net/play/rjaa_twr1.pls", favorite = false},
    {name = "SomaFM - DEF CON Radio", address = "http://ice1.somafm.com/defcon-128-mp3", favorite = nil},
    {name = "SomaFM - Digitalis", address = "http://ice1.somafm.com/digitalis-128-mp3", favorite = nil},
    {name = "SomaFM - Lush", address = "http://ice1.somafm.com/lush-128-mp3", favorite = nil},
    {name = "SomaFM - SF 10-33", address = "https://ice1.somafm.com/sf1033-128-mp3", favorite = nil},
    {name = "SomaFM - Secret Agent", address = "http://ice1.somafm.com/secretagent-128-mp3", favorite = nil},
    {name = "SomaFM - Space Station Soma", address = "http://ice1.somafm.com/spacestation-128-mp3", favorite = nil},
    {name = "SomaFM - Tiki Time", address = "http://ice1.somafm.com/tikitime-128-mp3", favorite = nil},
    -- add streams  {name = "", address = "", favorite = nil},
}