return {
    {name = "24/7 Bach", address = "http://38.96.148.28:8342/stream", favorite = nil},
    {name = "24/7 Bach", address = "http://38.96.148.28:8342/stream", favorite = nil},
    {name = "24-7 Best Of The 80's", address = "http://www.24-7nicheradio.com:8270/;", favorite = nil},
    {name = "24-7 Reggae", address = "http://24-7nicheradio.com:8200/", favorite = nil},
    {name = "24-7 Smooth Jazz", address = "http://146.71.124.10:8280/listen.pls?sid=1", favorite = nil},
    {name = "24.7 The Mix - Sudbury, ON", address = "http://46.105.126.68:7304/;stream.mp3", favorite = nil},
    {name = "Aljazeera English", address = "http://live-hls-web-aje.getaj.net/AJE/06.m3u8", favorite = nil},
    {name = "Angel Radio", address = "http://s8.viastreaming.net/cgi-bin/listen.pls?7030", favorite = nil},
    {name = "Angel Radio", address = "http://s8.viastreaming.net/7030/listen.m3u", favorite = nil},
    {name = "Angel Radio (HQ)", address = "http://s2.xrad.io:8522/listen.pls?sid=1", favorite = nil},
    {name = "Bartók Rádió", address = "http://mr-stream.mediaconnect.hu/4742/mr3hq.mp3", favorite = nil},
    {name = "BBC World Service", address = "https://stream.live.vc.bbcmedia.co.uk/bbc_world_service", favorite = nil},
    {name = "BBC World Service", address = "http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/http-icy-mp3-a/vpid/bbc_world_service/format/pls.pls", favorite = nil},
    {name = "BBC World Service", address = "http://stream.live.vc.bbcmedia.co.uk/bbc_world_service", favorite = nil},
    {name = "British Comedy Radio", address = "http://149.255.59.164:8009/", favorite = nil},
    {name = "Capital UK", address = "http://vis.media-ice.musicradio.com/CapitalUK", favorite = nil},
    {name = "Capital FM London", address = "http://media-ice.musicradio.com/CapitalMP3", favorite = nil},
    {name = "Classic FM UK", address = "http://media-the.musicradio.com/ClassicFM", favorite = nil},
    {name = "Classic FM", address = "http://ice-sov.musicradio.com/ClassicFMMP3", favorite = nil},
    {name = "Classic FM UK", address = "http://ice-the.musicradio.com/ClassicFMMP3", favorite = nil},
    {name = "Classic FM at the Movies", address = "http://media-sov.musicradio.com/ClassicFM-M-Movies", favorite = nil},
    {name = "Classic FM Relax", address = "http://media-the.musicradio.com/ClassicFM-M-Relax", favorite = nil},
    {name = "Classic Fm Soundtracks", address = "http://playerservices.streamtheworld.com/api/livestream-redirect/SRGSTR26.mp3", favorite = nil},
    {name = "Celtic Music Radio", address = "http://stream.celticmusicradio.net:8000/celticmusic.mp3", favorite = nil},
    {name = "Chill", address = "http://media-ice.musicradio.com/ChillMP3.m3u", favorite = nil},
    {name = "CHON 98.1 Northern Native Broadcasting - Whitehorse, YT", address = "http://stream.nnby.ca:8042/stream", favorite = nil},
    {name = "China Plus China Radio International CRI", address = "http://am846-lh.akamaihd.net/i/am846_1@301569/master.m3u8", favorite = nil},
    {name = "CRIè½»æ¾è°ƒé¢‘", address = "http://sk.cri.cn/915.m3u8", favorite = nil},
    {name = "CRI News Plus AM1008", address = "http://sk.cri.cn/am1008.m3u8", favorite = nil},
    {name = "Crime & Suspense", address = "http://streaming01.zfast.co.uk:8168/stream", favorite = nil},
    {name = "Danubius RÃ¡diÃ³", address = "http://stream.danubiusradio.hu/danubius_128k", favorite = nil},
    {name = "Danubius radio", address = "https://s04.diazol.hu:6022/live.mp3", favorite = nil},
    {name = "Danubius", address = "https://stream.danubiusradio.hu/danubius_320k", favorite = nil},
    {name = "Deep House Lounge", address = "http://198.15.94.34:8006/stream", favorite = nil},
    {name = "Express FM 93.7 Portsmouth", address = "http://london-ics01.broadcast.meteoric.net/expressfm.mp3?.mp3", favorite = nil},
    {name = "Future Radio 107.8 Norwich", address = "http://futureradio.co.uk/Future.m3u", favorite = nil},
    {name = "England - Heart London Radio", address = "http://ice-the.musicradio.com/HeartLondonMP3", favorite = nil},
    {name = "Heart Dorset 102.3", address = "http://ice-sov.musicradio.com/HeartDorsetMP3", favorite = nil},
    {name = "Heart South Coast 96.7 & 97.5", address = "http://media-sov.musicradio.com/HeartHampshire", favorite = nil},
    {name = "Heart Sussex 102.4 &103.5", address = "http://media-ice.musicradio.com/HeartSussexMP3?.mp3", favorite = nil},
    {name = "HTM eco RADIO", address = "https://azuracast.htmecoradio.com/radio/8000/htm.mp3", favorite = nil},
    {name = "I Love PÃ©cs RÃ¡diÃ³", address = "http://radio.ilovepecs.hu:8200/ilp.mp3", favorite = nil},
    {name = "JAZZ & CHILL", address = "http://salalondon.ddns.net:8002/;.m3u", favorite = nil},
    {name = "Jazz London Radio", address = "http://radio.canstream.co.uk:8075/live.mp3", favorite = nil},
    {name = "Jazz 24 Seattle", address = "http://live.wostreaming.net/direct/ppm-jazz24mp3-ibc1?source=TuneIn", favorite = nil},
    {name = "Joint Radio Reggae", address = "http://star.jointil.net/proxy/jrn_reggae?mp=/stream", favorite = nil},
    {name = "KLASSIK 1", address = "http://icepool.silvacast.com/KLASSIK1.mp3", favorite = nil},
    {name = "Klassikradio", address = "http://stream.klassikradio.de/live/mp3-192/stream.klassikradio.de/", favorite = nil},
    {name = "Klassik Radio - Barock", address = "http://stream.klassikradio.de/barock/mp3-192", favorite = nil},
    {name = "Klassik Radio - Friends@Home", address = "http://stream.klassikradio.de/friendshome/mp3-128/", favorite = nil},
    {name = "Klassikradio - Chor", address = "http://stream.klassikradio.de/chor/mp3-192/www.klassikradio.de/", favorite = nil},
    {name = "Klassikradio - Christmas / Weihnachten", address = "https://klassikr.streamabc.net/klr-christmas-mp3-192-8981917?sABC=5p210oso%230%23926583or7n8n236724or510opqn136no%23zvdhvqb&amsparams=playerid:miquido;skey:1545669627", favorite = nil},
    {name = "Klassik Radio - Healing", address = "http://stream.klassikradio.de/healing/mp3-128/", favorite = nil},
    {name = "Klassik Radio - Klassik Dreams", address = "http://stream.klassikradio.de/dreams/mp3-128/", favorite = nil},
    {name = "Hirschmilch Radio Prog-House", address = "https://hirschmilch.de:7001/prog-house.mp3", favorite = nil},
    {name = "Klassik Radio - Klassik Lounge mit Schiller", address = "http://stream.klassikradio.de/schiller/mp3-320", favorite = nil},
    {name = "Klassik Radio - Legenden der Klassik", address = "http://stream.klassikradio.de/legenden/mp3-128", favorite = nil},
    {name = "Klassik Radio - Lounge", address = "http://stream.klassikradio.de/lounge/mp3-128/www.klassikradio.de/", favorite = nil},
    {name = "Klassikradio - Movie Channel", address = "http://stream.klassikradio.de/movie/mp3-192/www.klassikradio.de/", favorite = nil},
    {name = "Klassik Radio - Nature", address = "http://stream.klassikradio.de/nature/mp3-128/www.klassikradio.de/", favorite = nil},
    {name = "Klassikradio - New Classics", address = "http://stream.klassikradio.de/newclassics/mp3-192/www.klassikradio.de/", favorite = nil},
    {name = "Klassik Radio - New Classics", address = "https://stream.klassikradio.de/newclassics/mp3/Miquido", favorite = nil},
    {name = "Klassik Radio - Opera", address = "http://stream.klassikradio.de/opera/mp3-128/www.klassikradio.de/", favorite = nil}, 
    {name = "Klassik Radio - Piano", address = "http://stream.klassikradio.de/piano/mp3-320", favorite = nil},
    {name = "Klassikradio - Pure Bach", address = "http://stream.klassikradio.de/purebach/mp3-192/www.klassikradio.de/", favorite = nil},
    {name = "Klassik Radio - Smooth", address = "http://stream.klassikradio.de/smooth/mp3-128/radiosure/play.m3u", favorite = nil},
    {name = "Laser Hot Hits", address = "http://213.175.217.198:8000/laserhq", favorite = nil},
    {name = "LBC Radio", address = "http://media-sov.musicradio.com/LBC973MP3Low", favorite = nil},
    {name = "LBC London (London stream) AAC", address = "http://media-sov.musicradio.com/LBCLondon", favorite = nil},
    {name = "Life Radio Tirol", address = "http://194.232.200.164:8000/;638826246082377stream.nsv", favorite = nil},
    {name = "Linn Classical", address = "http://89.16.185.174:8004/stream", favorite = nil},
    {name = "Linn Jazz", address = "http://89.16.185.174:8000/stream", favorite = nil},
    {name = "Linn Radio", address = "http://radio.linnrecords.com/cast/tunein.php/linnradio/playlist.pls", favorite = nil},
    {name = "Live Radio Tirol", address = "https://liferadiotirol.apa.at:8000/", favorite = nil},
    {name = "Mechanical Music Radio", address = "http://net1.citrus3.com:8978/;stream.mp3", favorite = nil},
    {name = "Naim Classical", address = "http://mscp3.live-streams.nl:8250/class-flac.flac", favorite = nil},
    {name = "Naim Classical", address = "http://mscp3.live-streams.nl:8250/class-high.aac", favorite = nil},
    {name = "Naim Jazz", address = "http://mscp3.live-streams.nl:8340/jazz-flac.flac", favorite = nil},
    {name = "Naim Jazz [320k aac]", address = "http://mscp3.live-streams.nl:8340/jazz-high.aac", favorite = nil},
    {name = "Naim Radio [lossless flac]", address = "http://mscp3.live-streams.nl:8360/flac.flac", favorite = nil},
    {name = "Naim Radio [320k aac]", address = "https://mscp3.live-streams.nl:8362/high.aac", favorite = nil},
    {name = "Naim Radio [320k aac]", address = "http://mscp3.live-streams.nl:8360/high.aac", favorite = nil},
    {name = "ORF Tirol http", address = "http://orf-live.ors-shoutcast.at/tir-q2a", favorite = nil},
    {name = "ORF Tirol http1", address = "http://orf-live.ors-shoutcast.at/tir-q1a", favorite = nil},
    {name = "Pinoy Radio UK", address = "http://206.72.194.250:9972/;stream.mp3", favorite = nil},
    {name = "Point Blank FM 320KB", address = "http://pointblankradio.co.uk:9002/stream", favorite = nil},
    {name = "Psychedelicized Radio", address = "http://s1.castserver.net:8006/", favorite = nil},
    {name = "radioalfa3 latin hits", address = "http://stream.zeno.fm/pexep60uhnruv", favorite = nil},
    {name = "Radio Caroline AAC 96 kbps", address = "http://78.129.202.200:8030/;", favorite = nil},
    {name = "Radio Caroline", address = "http://sc6.radiocaroline.net:8040/;stream.mp3", favorite = nil},
    {name = "Radio Caroline", address = "http://78.129.202.200:8040/;", favorite = nil},
    {name = "Radio Caroline Flashback", address = "http://sc2.radiocaroline.net:10558/listen.pls", favorite = nil},
    {name = "Radio Caroline 259 Gold", address = "http://95.211.66.140:8253/", favorite = nil},
    {name = "Radio Mirchi - English Love", address = "https://radioromancehdli-lh.akamaihd.net/i/RadioRomanceHDLive_1_1@334956/master.m3u8", favorite = nil},
    {name = "Radio Mirchi - English Retro", address = "https://cassetteclassics-lh.akamaihd.net/i/CassClassicsHDLive_1_1@334553/master.m3u8", favorite = nil},
    {name = "Radio Northsea International", address = "http://radionorthsea.zapto.org:8008/listen.pls", favorite = nil},
    {name = "RNI Radio Northsea Inbternational", address = "http://stream.radio-northsea.de:7000/mp3", favorite = nil},
    {name = "Radio Northsea International", address = "http://188.40.135.197:8388/", favorite = nil},
    {name = "Radio Paradise (320k)", address = "http://stream-uk1.radioparadise.com/aac-320", favorite = nil},
    {name = "Radio Osttirol", address = "http://streamplus20.leonex.de:28768/;", favorite = nil},
    {name = "Radio Seagull", address = "http://nednl.net:8000/seagull", favorite = nil},
    {name = "Radio Tirol", address = "http://str2.creacast.com/radiotirol_a", favorite = nil},
    {name = "Rai SÃ¼dtirol (TV)", address = "http://wzstreaming.rai.it/TVlive/liveStream/playlist.m3u8", favorite = nil},
    {name = "Rai SÃ¼dtirol", address = "http://radiobzlive.rai.it/RAIBZ_Livestream", favorite = nil},
    {name = "Reggae Radio Rastamusic.com", address = "http://ais.rastamusic.com/rastamusic.mp3.m3u", favorite = nil},
    {name = "RFI Anglais - English", address = "http://live02.rfi.fr/rfienanglais-64.mp3", favorite = nil},
    {name = "Rock Antenne - Heavy Metal", address = "http://mp3channels.webradio.rockantenne.de/heavy-metal", favorite = nil},
    {name = "RTL", address = "http://streaming.radio.rtl.fr/rtl-1-44-128", favorite = nil},
    {name = "Sea Haven FM 96.3 Seaford, East Sussex", address = "http://195.10.228.6:8027/live.mp3", favorite = nil},
    {name = "SomaFM Beat Blender (128k AAC)", address = "https://somafm.com/beatblender130.pls", favorite = nil},
    {name = "Somafm Dub Step Beyond", address = "https://somafm.com/dubstep32.pls", favorite = nil},
    {name = "SomaFM Dub Step Beyond", address = "http://ice3.somafm.com/dubstep-128-mp3", favorite = nil},
    {name = "SomaFM Dub Step Beyond", address = "http://ice3.somafm.com/dubstep-128-aac", favorite = nil},
    {name = "SomaFM Deep Space One 128k AAC+", address = "http://ice1.somafm.com/deepspaceone-128-aac", favorite = nil},
    {name = "SomaFM Deep Space One 128k MP3", address = "https://somafm.com/deepspaceone.pls", favorite = nil},
    {name = "SomaFM Deep Space One", address = "https://somafm.com/deepspaceone32.pls", favorite = nil},
    {name = "SomaFM Deep Space One", address = "http://ice1.somafm.com/deepspaceone-64-aac", favorite = nil},
    {name = "SomaFM Drone Zone 128k AAC", address = "http://ice3.somafm.com/dronezone-128-aac", favorite = nil},
    {name = "SomaFM Drone Zone 128k MP3", address = "http://somafm.com/dronezone.pls", favorite = nil},
    {name = "SomaFM Drone Zone 256k MP3", address = "http://ice1.somafm.com/dronezone-256-mp3", favorite = nil},
    {name = "Somafm Fluid", address = "https://somafm.com/fluid32.pls", favorite = nil},
    {name = "SomaFM Fluid", address = "https://somafm.com/fluid.pls", favorite = nil},
    {name = "SomaFM Fluid (128K AAC)", address = "http://somafm.com/fluid130.pls", favorite = nil},
    {name = "SomaFM Groove Salad", address = "http://ice3.somafm.com/groovesalad-128-mp3", favorite = nil},
    {name = "SomaFM Groove Salad 128k AAC", address = "http://somafm.com/groovesalad130.pls", favorite = nil},
    {name = "SomaFM Groove Salad Classic 128k", address = "https://somafm.com/gsclassic.pls", favorite = nil},
    {name = "SomaFM Indie Pop Rocks! - AAC 128k", address = "http://ice3.somafm.com/indiepop-128-aac", favorite = nil},
    {name = "SomaFM Secret Agent - AAC 128k", address = "http://ice3.somafm.com/secretagent-128-aac", favorite = nil},
    {name = "SomaFM Secret Agent", address = "http://ice.somafm.com/secretagent", favorite = nil},
    {name = "SomaFM Sonic Universe 192k MP3", address = "http://somafm.com/sonicuniverse192.pls", favorite = nil},
    {name = "SomaFM Sonic Universe 128k AAC+", address = "https://somafm.com/sonicuniverse130.pls", favorite = nil},
    {name = "Sputnik News English (USA)", address = "http://audio1.video.ria.ru/voiceusa", favorite = nil},
    {name = "Station X - Northern Soul And Motown", address = "http://91.121.205.70:4000/;", favorite = nil},
    {name = "Südtirol 1", address = "http://players.creacast.com/creacast/sudtirol1a/playlist.pls", favorite = nil},
    {name = "Swinging Radio England (S.R.E.)", address = "http://c24.radioboss.fm:8017/stream", favorite = nil},
    {name = "talkRADIO", address = "http://radio.talkradio.co.uk/stream", favorite = nil},
    {name = "The English Connection Media", address = "http://s30.myradiostream.com:19108/listen.mp3", favorite = nil},
    {name = "Traffic Music Radio", address = "http://162.244.80.106:8091/stream", favorite = nil},
    {name = "Unity 101 Community Radio", address = "http://live.canstream.co.uk:8000/unity24.mp3", favorite = nil},
    {name = "Virgin Radio Chilled", address = "https://radio.virginradio.co.uk/stream-chilled", favorite = nil},
    {name = "VOA1 - The Hits", address = "http://voa-22.akacast.akamaistream.net/7/48/322034/v1/ibb.akacast.akamaistream.net/voa-22", favorite = nil},
    {name = "VOA Voice of America Global English", address = "http://voa-28.akacast.akamaistream.net/7/54/322040/v1/ibb.akacast.akamaistream.net/voa-28", favorite = nil},
    {name = "VOA Chinese", address = "http://voa-11.akacast.akamaistream.net/7/317/322023/v1/ibb.akacast.akamaistream.net/voa-11", favorite = nil},
    {name = "VOA-Voice of America African Service (English)", address = "http://voa-17.akacast.akamaistream.net/7/315/322029/v1/ibb.akacast.akamaistream.net/voa-17", favorite = nil},
}

















