-- DO NOT TRY to hide a stream from your station list by removing it from this file. It will be deleted from the table
return {
    {name = "Birdsong.fm", address = "https://streaming-saltlakecity1.radio.co/s5c5da6a36/listen", favorite = false},
    {name = "HF CAR-B: 11.330", address = "https://www.liveatc.net/play/hf_nh_11330.pls", favorite = false},
    {name = "HF NAT-B 5616/8864 NH", address = "https://www.liveatc.net/play/hf_atlantic_b.pls", favorite = false},
    {name = "NTS - (unlisted)", address = "https://stream-relay-geo.ntslive.net/mixtape7", favorite = false},
    {name = "NTS - 4 to the Floor", address = "https://stream-mixtape-geo.ntslive.net/mixtape5", favorite = false},
    {name = "NTS - Expansions", address = "https://stream-mixtape-geo.ntslive.net/mixtape3", favorite = false},
    {name = "NTS - Feelings", address = "https://stream-relay-geo.ntslive.net/mixtape27", favorite = false},
    {name = "NTS - Field Recordings", address = "https://stream-relay-geo.ntslive.net/mixtape23", favorite = false},
    {name = "NTS - Island Time", address = "https://stream-relay-geo.ntslive.net/mixtape21", favorite = false},
    {name = "NTS - Labyrinth", address = "https://stream-relay-geo.ntslive.net/mixtape31", favorite = false},
    {name = "NTS - Low Key", address = "https://stream-relay-geo.ntslive.net/mixtape2", favorite = false},
    {name = "NTS - Memory Lane", address = "https://stream-mixtape-geo.ntslive.net/mixtape6", favorite = false},
    {name = "NTS - Poolside", address = "https://stream-mixtape-geo.ntslive.net/mixtape4", favorite = false},
    {name = "NTS - Radio 1", address = "https://stream-relay-geo.ntslive.net/stream", favorite = false},
    {name = "NTS - Radio 2", address = "https://stream-relay-geo.ntslive.net/stream2", favorite = false},
    {name = "NTS - Rap House", address = "https://stream-relay-geo.ntslive.net/mixtape22", favorite = false},
    {name = "NTS - Sheet Music", address = "https://stream-relay-geo.ntslive.net/mixtape35", favorite = false},
    {name = "NTS - Slow Focus", address = "https://stream-relay-geo.ntslive.net/mixtape", favorite = false},
    {name = "NTS - Sweat", address = "https://stream-relay-geo.ntslive.net/mixtape24", favorite = false},
    {name = "NTS - The Pit", address = "https://stream-relay-geo.ntslive.net/mixtape34", favorite = false},
    {name = "NTS - The Tube", address = "https://stream-relay-geo.ntslive.net/mixtape26", favorite = false},
    {name = "Nectarine Demoscene Radio", address = "https://radio.worlio.com/stream/necta192.mp3", favorite = nil},
    {name = "Novosibirsk Gnd/Twr/App/Radar/Misc", address = "https://www.liveatc.net/play/unnt.pls", favorite = false},
    {name = "Partytronic", address = "https://partytronic.com", favorite = nil},
    {name = "RJAA Tower 1", address = "https://www.liveatc.net/play/rjaa_twr1.pls", favorite = false},
    {name = "Radio Aporee", address = "http://radio.aporee.org:8000/aporee.m3u", favorite = nil},
    {name = "Radio Nintendo", address = "http://Play.RadioNintendo.com:8000/stream", favorite = nil},
    {name = "SceneStat - Demoscene", address = "https://SceneSat.com/listen/port80/mid.m3u", favorite = nil},
    {name = "SomaFM - DEF CON Radio", address = "http://ice1.somafm.com/defcon-128-mp3", favorite = nil},
    {name = "SomaFM - Deep Space One", address = "https://somafm.com/deepspaceone.pls", favorite = nil},
    {name = "SomaFM - Digitalis", address = "http://ice1.somafm.com/digitalis-128-mp3", favorite = nil},
    {name = "SomaFM - Drone Zone", address = "https://somafm.com/dronezone.pls", favorite = nil},
    {name = "SomaFM - Groove Salad", address = "https://somafm.com/groovesalad.pls", favorite = nil},
    {name = "SomaFM - Groove Salad Classic", address = "https://somafm.com/gsclassic.pls", favorite = nil},
    {name = "SomaFM - Illinois Street Lounge", address = "http://ice1.somafm.com/illstreet-128-mp3", favorite = nil},
    {name = "SomaFM - Lush", address = "http://ice1.somafm.com/lush-128-mp3", favorite = nil},
    {name = "SomaFM - SF 10-33", address = "https://ice1.somafm.com/sf1033-128-mp3", favorite = false},
    {name = "SomaFM - SF in SF", address = "https://somafm.com/sfinsf.pls", favorite = nil},
    {name = "SomaFM - Secret Agent", address = "http://ice1.somafm.com/secretagent-128-mp3", favorite = nil},
    {name = "SomaFM - Sonic Universe", address = "http://ice1.somafm.com/sonicuniverse-128-mp3", favorite = nil},
    {name = "SomaFM - Space Station Soma", address = "http://ice1.somafm.com/spacestation-128-mp3", favorite = nil},
    {name = "SomaFM - Suburbs of Goa", address = "http://ice1.somafm.com/suburbsofgoa-128-mp3", favorite = nil},
    {name = "SomaFM - The Trip", address = "http://ice1.somafm.com/thetrip-128-mp3", favorite = nil},
    {name = "SomaFM - Tiki Time", address = "http://ice1.somafm.com/tikitime-128-mp3", favorite = false},
    {name = "SomaFM - n5MD Radio", address = "https://somafm.com/n5md.pls", favorite = nil},
    {name = "SomaFM - Mission Control", address = "https://somafm.com/missioncontrol.pls", favorite = nil},
    {name = "SomaFM - cliqhop idm", address = "https://somafm.com/cliqhop.pls", favorite = false},
    -- add streams  {name = "", address = "", favorite = nil},
}